### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by pabloariasal** [OliverLew/fontpreview-ueberzug#1]
Really like this tool, good job! In fact I like it so much that would like to create an AUR package to make installation easier for all Arch-based distros, for this however, the repo needs to have a License.

**Comment by OliverLew** [comment]
Added.
And a AUR package would be awesome, appreciate it!

**Comment by pabloariasal** [comment]
Done! https://aur.archlinux.org/packages/fontpreview-ueberzug-git
