### ISSUE TITLE
Info regarding script

### ISSUE THREAD

**Issue by pystardust** [OliverLew/fontpreview-ueberzug#13]
Hey, I would like to understand a bit of whats happening when you start and stop ueberzug. The part I am confused on is the place where you redirected `3` to `$FIFO`. The url provided seems to have been expired.

**Comment by OliverLew** [comment]
I think that is to prevent the fifo from closing. I didn't know what it is doing at all at the time I was writing this, that's why I commented with the url I borrowed it from :)

The author of ueberzug closed the issue entry overall so we can't see the url page now.

**Comment by pystardust** [comment]
Thanks for the amazing script.
I referred a part of your script to help me out with ytfzf (  https://github.com/pystardust/ytfzf ) .
Many people are facing issues with ueberzug. 
Especially the ones who are not using X (ie wayland). 
And also it seems to be buggy with fish shell. It seems to be dodgy to get ueberzug work in posix.

**Comment by pystardust** [comment]
Okay I understood how that works now. I tried using ` <> $FIFO` so that the pipe always stays open. But there seems to be no way to stop ueberzug after that, other than killing it with pid.

**Comment by OliverLew** [comment]
Glad it helps :) Haven't noticed `ytfzf` is your project! Saw it on r/unixporn couple of days ago, it's really cool!

**Comment by pystardust** [comment]
All thanks to you! :)
