### ISSUE TITLE
Text Alignment option

### ISSUE THREAD

**Issue by lucypero** [OliverLew/fontpreview-ueberzug#14]
It would be nice if there were an option to change the text alignment, as I use this to preview how code would look on different fonts. Something like `-a left/center/right`

**Comment by OliverLew** [comment]
Sure, it can be done with `-gravity` option of `convert`, I'll push a commit soon.

**Comment by OliverLew** [comment]
I hardcoded the padding thinking that should be okay. You can try the latest commit and see if it works.

**Comment by lucypero** [comment]
Works great! Thank you! 😁

**Comment by OliverLew** [comment]
Great! I will then close this issue then
