### ISSUE TITLE
convert: unable to read font '/usr/share/fonts/<random letters and numbers>/<even more>.pcf.gz @ annotate/annotate.c/RenderFreetype/1483

### ISSUE THREAD

**Issue by alx365** [OliverLew/fontpreview-ueberzug#4]
OS: archlinux, newest version of all packages

When i start fontpreview, i get greeted with the error message, that is shown in the title, that error message comes with c.a. 75% of all fonts, and with the other ones, there is no output on the left.

I have all of the dependencies installed.

**Comment by OliverLew** [comment]
Yes, it current does that. ImageMagick's `convert` command do not use `.pcf` fonts. I should probably use `convert -list font` to list the available fonts, so every font shows in `fontpreview-ueberzug` can be, well, previewed. I will solve it after I figure out how to do that elegantly.

**Comment by OliverLew** [comment]
It should be fixed in the latest master. There are still some fonts `convert` finds but give errors in the command. We can reopen if there is any more issues.

BTW, currently it shows font name differently.
