### ISSUE TITLE
Preview window/process left open after exit

### ISSUE THREAD

**Issue by Strahinja** [OliverLew/fontpreview-ueberzug#8]
I'm using the latest version of [package fontpreview-ueberzug-git][1] from AUR, which is r32.a083d3a-1, on the latest Artix Linux, and in the latest version of that package font preview window stays open even after exiting the fontpreview-ueberzug program by pressing Esc. Also a process with the command line `/usr/bin/python /usr/bin/ueberzug layer --parser simple --silent` is left open. When killed (for example, by `pskill -9 ueberzug`, the parameter `-9` is necessary), the leftover preview window disappears. This was a [known][2] [issue][3] in ueberzug, which was subsequently fixed, but it seems it doesn't propagate to fontpreview-ueberzug-git.

[1]: https://aur.archlinux.org/packages/fontpreview-ueberzug-git/
[2]: https://github.com/seebye/ueberzug/issues/125
[3]: https://github.com/seebye/ueberzug/pull/119

**Comment by OliverLew** [comment]
Just checked, I am having this now, too :joy: No idea why tho.

**Comment by OliverLew** [comment]
@Strahinja, Possible `ueberzug` issue: https://github.com/seebye/ueberzug/issues/127
Let's wait for the author to confirm and resolve it.

**Comment by OliverLew** [comment]
The upstream issue has been resolved, we just have to either install the master branch of `ueberzug` or wait for a new release.
Closing this issue now.
